### ISSUE TITLE
Monday

### ISSUE THREAD

**Issue by anna08test** [Org1Watson/RepoWatson1#5]

**Comment by status-open-bounty** [comment]
Balance: 0.0200 ETH
Contract address: [0xaa75c6224373ba9a8e038ee3562f5871de70ec11](https://ropsten.etherscan.io/address/0xaa75c6224373ba9a8e038ee3562f5871de70ec11)
Network: Testnet (Ropsten)
Status: pending maintainer confirmation
Winner: annadanchenko
